"""
Mapping dictionary to link Postal Cities (Rental Data) to Political Communes (Tax Data).
Source: Manual Entity Resolution based on Swiss Federal Statistical Office & Wikipedia.
"""

CITY_TO_COMMUNE_MAP = {
    # AG
    'aarau rohr': 'aarau',
    'ammerswil ag': 'ammerswil',
    'anglikon': 'wohlen (ag)',
    'arni': 'arni (ag)',
    'arni ag': 'arni (ag)',
    'bad zurzach': 'zurzach',
    'baden-dättwil': 'baden',
    'benzenschwil': 'merenschwand',
    'birmenstorf ag': 'birmenstorf (ag)',
    'bremgarten': 'bremgarten (ag)',
    'bremgarten ag': 'bremgarten (ag)',
    'brugg ag': 'brugg',
    'buchs': 'buchs (ag)',  # Context dependent, defaulting to AG if AG input
    'buchs ag': 'buchs (ag)',
    'büttikon ag': 'büttikon',
    'dättwil ag': 'baden',
    'erlinsbach': 'erlinsbach (ag)',
    'fenkrieden': 'sins',
    'hausen ag': 'hausen (ag)',
    'hermetschwil': 'bremgarten (ag)',
    'hertenstein ag': 'obersiggenthal',
    'hilfikon': 'villmergen',
    'ittenthal': 'kaisten',
    'kaiserstuhl ag': 'kaiserstuhl',
    'kirchdorf': 'obersiggenthal',
    'kirchdorf ag': 'obersiggenthal',
    'kleindöttingen': 'böttstein',
    'küngoldingen': 'oftringen',
    'leimbach ag': 'leimbach (ag)',
    'lengnau ag': 'lengnau (ag)',
    'lunkhofen': 'oberlunkhofen',
    'muri': 'muri (ag)',
    'muri ag': 'muri (ag)',
    'möriken ag': 'möriken-wildegg',
    'münchwilen': 'münchwilen (ag)',
    'münchwilen ag': 'münchwilen (ag)',
    'niederwil ag': 'niederwil (ag)',
    'nussbaumen ag': 'obersiggenthal',
    'nussbaumen b.baden': 'obersiggenthal',
    'oberwil-lieli': 'oberwil-lieli',
    'reinach': 'reinach (ag)',
    'reinach ag': 'reinach (ag)',
    'rekingen': 'zurzach',
    'rekingen ag': 'zurzach',
    'rietheim': 'zurzach',
    'rombach': 'küttigen',
    'rudolfstetten': 'rudolfstetten-friedlisberg',
    'rümikon ag': 'zurzach',
    'rütihof': 'baden',
    'siggenthal station': 'untersiggenthal',
    'sisseln ag': 'sisseln',
    'stein': 'stein (ag)',
    'stein ag': 'stein (ag)',
    'stetten ag': 'stetten (ag)',
    'stilli': 'villigen',
    'tennwil': 'meisterschwanden',
    'teufenthal': 'teufenthal (ag)',
    'teufenthal ag': 'teufenthal (ag)',
    'turgi': 'baden',
    'umiken': 'brugg',
    'unterlunkhofen': 'unterlunkhofen',
    'wildegg': 'möriken-wildegg',
    'wohlen': 'wohlen (ag)',
    'wohlen ag': 'wohlen (ag)',

    # BE
    'allmendingen bei bern': 'allmendingen',
    'belprahon': 'belprahon',
    'berne': 'bern',
    'biel': 'biel/bienne',
    'biel (be)': 'biel/bienne',
    'biel / bienne': 'biel/bienne',
    'biel, bienne': 'biel/bienne',
    'biel-vingelz': 'biel/bienne',
    'bienne': 'biel/bienne',
    'boll': 'vechigen',
    'bremgarten b. bern': 'bremgarten bei bern',
    'busswil': 'lyss',
    'busswil be': 'lyss',
    'bärau': 'langnau im emmental',
    'bäriswil be': 'bäriswil',
    'bützberg': 'thunstetten',
    'emmenmatt': 'lauperswil',
    'faulensee': 'spiez',
    'gasel': 'köniz',
    'goldiwil (thun)': 'thun',
    'gstaad': 'saanen',
    'gumligen': 'muri bei bern',
    'gümligen': 'muri bei bern',
    'gümmenen': 'mühleberg',
    'gwatt (thun)': 'thun',
    'hasle b. burgdorf': 'hasle bei burgdorf',
    'helgisried-rohrbach': 'rüeggisberg',
    'herrenschwanden': 'kirchlindach',
    'hinterkappelen': 'wohlen bei bern',
    'hünibach': 'hilterfingen',
    'innerberg': 'wohlen bei bern',
    'kirchberg': 'kirchberg (be)',
    'kirchberg be': 'kirchberg (be)',
    'kleindietwil': 'madiswil',
    'langnau': 'langnau im emmental',
    'langnau i. e.': 'langnau im emmental',
    'laupen be': 'laupen',
    'lengnau': 'lengnau (be)',
    'lengnau be': 'lengnau (be)',
    'lenk im simmental': 'lenk',
    'liebefeld': 'köniz',
    'lätti': 'rapperswil (be)',
    'lützelflüh - goldbach': 'lützelflüh',
    'lützelflüh-goldbach': 'lützelflüh',
    'mamishaus': 'schwarzenburg',
    'muri': 'muri bei bern',
    'muri b. bern': 'muri bei bern',
    'mühledorf be': 'kirchdorf (be)',
    'münster (be)': 'bern',
    'neuenstadt': 'la neuveville',
    'niederried b. interlaken': 'niederried bei interlaken',
    'niederscherli': 'köniz',
    'niederwangen be': 'köniz',
    'niederwangen b. bern': 'köniz',
    'oberfrittenbach': 'langnau im emmental',
    'oberwangen b. bern': 'köniz',
    'oey': 'diemtigen',
    'ortschwaben': 'meikirch',
    'ostermundigen sb': 'ostermundigen',
    'péry': 'péry-la heutte',
    'rapperswil': 'rapperswil (be)',
    'ried (frutigen)': 'frutigen',
    'riffenmatt': 'guggisberg',
    'roggwil': 'roggwil (be)',
    'roggwil be': 'roggwil (be)',
    'rosshäusern': 'mühleberg',
    'rüfenacht': 'worb',
    'rüfenacht be': 'worb',
    'rüti b. büren': 'rüti bei büren',
    'schliern b. köniz': 'köniz',
    'schwendibach': 'steffisburg',
    'schönbühl': 'urtenen-schönbühl',
    'seedorf': 'seedorf (be)',
    'seedorf be': 'seedorf (be)',
    'siselen be': 'siselen',
    'spiegel b. bern': 'köniz',
    'st-imier': 'saint-imier',
    'studen': 'studen (be)',
    'studen be': 'studen (be)',
    'sutz': 'sutz-lattrigen',
    'säriswil': 'wohlen bei bern',
    'thörishaus': 'köniz',
    'twann': 'twann-tüscherz',
    'tüscherz-alfermée': 'twann-tüscherz',
    'uettligen': 'wohlen bei bern',
    'utzigen': 'vechigen',
    'wabern': 'köniz',
    'wanzwil': 'herzogenbuchsee',
    'wasen im emmental': 'sumiswald',
    'wiler b. utzenstorf': 'wiler bei utzenstorf',
    'wohlen b. bern': 'wohlen bei bern',
    'worblaufen': 'ittigen',
    'zollbrück': 'rüderswil',

    # BL
    'aesch': 'aesch (bl)',
    'aesch bl': 'aesch (bl)',
    'biel-benken bl': 'biel-benken',
    'kanton reinach': 'reinach (bl)',
    'liesberg dorf': 'liesberg',
    'oberdorf': 'oberdorf (bl)',
    'oberdorf bl': 'oberdorf (bl)',
    'oberwil': 'oberwil (bl)',
    'oberwil bl': 'oberwil (bl)',
    'reinach': 'reinach (bl)',
    'reinach bl': 'reinach (bl)',
    'rickenbach bl': 'rickenbach (bl)',
    'wahlen b. laufen': 'wahlen',

    # BS
    'bâle': 'basel',

    # FR
    'arconciel': 'bois-d\'amont',
    'alterswil fr': 'tafers',
    'avry-sur-matran': 'avry',
    'billens': 'billens-hennens',
    'bussy fr': 'estavayer',
    'châtel-st-denis': 'châtel-saint-denis',
    'châtillon fr': 'châtillon (fr)',
    'cordast': 'gurmels',
    'corpataux': 'gibloux',
    'cottens': 'cottens (fr)',
    'cottens fr': 'cottens (fr)',
    'cournillens': 'misery-courtion',
    'cressier': 'cressier (fr)',
    'domdidier': 'belmont-broye',
    'dompierre fr': 'belmont-broye',
    'ecuvillens': 'hauterive (fr)',
    'estavayer-le-lac': 'estavayer',
    'farvagny-le-grand': 'gibloux',
    'flamatt': 'wünnewil-flamatt',
    'freiburg': 'fribourg',
    'galmiz': 'murten',
    'gempenach': 'murten',
    'la tour-de-trême': 'bulle',
    'le pâquier-montbarry': 'le pâquier (fr)',
    'les paccots': 'châtel-saint-denis',
    'léchelles': 'belmont-broye',
    'môtier (vully)': 'mont-vully',
    'murist': 'estavayer',
    'neyruz': 'neyruz (fr)',
    'neyruz fr': 'neyruz (fr)',
    'posieux': 'hauterive (fr)',
    'prez-vers-noréaz': 'prez',
    'rossens fr': 'gibloux',
    'rueyres-st-laurent': 'gibloux',
    'salvenach': 'murten',
    'schmitten': 'schmitten (fr)',
    'schmitten fr': 'schmitten (fr)',
    'schwarzsee': 'plaffeien',
    'st-aubin fr': 'saint-aubin (fr)',
    'st. antoni': 'tafers',
    'sugiez': 'mont-vully',
    'villarepos': 'courtepin',
    'villeneuve fr': 'surpierre',
    'vuippens': 'marsens',
    'wünnewil': 'wünnewil-flamatt',

    # GE
    'aïre': 'vernier',
    'athenaz (avusy)': 'avusy',
    'carouge': 'carouge (ge)',
    'carouge ge': 'carouge (ge)',
    'chambésy': 'pregny-chambésy',
    'champel': 'genève',
    'charmilles-châtelaine': 'genève',
    'châtelaine': 'vernier',
    'cointrin': 'meyrin',
    'conches': 'chêne-bougeries',
    'corsier': 'corsier (ge)',
    'corsier ge': 'corsier (ge)',
    'eaux-vives-lac': 'genève',
    'geneva': 'genève',
    'genf': 'genève',
    'ginevra': 'genève',
    'grand-lancy': 'lancy',
    'la croix-de-rozon': 'bardonnex',
    'le petit-saconnex': 'genève',
    'les acacias': 'genève',
    'les avanchets': 'vernier',
    'perly': 'perly-certoux',
    'petit-lancy': 'lancy',
    'plainpalais': 'genève',
    'pâquis': 'genève',
    'saint-jean-aire': 'genève',
    'sézegnin': 'avusy',
    'vessy': 'veyrier',
    'vésenaz': 'collonge-bellerive',

    # GL
    'bilten': 'glarus nord',
    'braunwald': 'glarus süd',
    'ennenda': 'glarus',
    'linthal': 'glarus süd',
    'luchsingen': 'glarus süd',
    'mitlödi': 'glarus süd',
    'mollis': 'glarus nord',
    'netstal': 'glarus',
    'niederurnen': 'glarus nord',
    'näfels': 'glarus nord',
    'riedern': 'glarus',
    'rüti gl': 'glarus süd',
    'schwanden gl': 'glarus süd',
    'schwändi b. schwanden': 'glarus süd',
    'ziegelbrücke': 'glarus nord',

    # GR
    'davos dorf': 'davos',
    'davos monstein': 'davos',
    'davos platz': 'davos',
    'flims waldhaus': 'flims',
    'haldenstein': 'chur',
    'igis': 'landquart',
    'ilanz': 'ilanz/glion',
    'klosters dorf': 'klosters',
    'klosters-serneus': 'klosters',
    'laax gr': 'laax',
    'lenzerheide/lai': 'vaz/obervaz',
    'malix': 'churwalden',
    'obersaxen': 'obersaxen mundaun',
    'parpan': 'churwalden',
    'riom': 'surses',
    'roveredo': 'roveredo (gr)',
    'roveredo gr': 'roveredo (gr)',
    's. bernardino': 'mesocco',
    's. vittore': 'san vittore',
    'savognin': 'surses',
    'schuls': 'scuol',
    'sedrun': 'tujetsch',
    'seewis dorf': 'seewis im prättigau',
    'st. moritz bad': 'st. moritz',
    'stierva': 'surses',
    'tinizong': 'surses',
    'tumegl/tomils': 'domleschg',
    'valbella': 'vaz/obervaz',
    'vella': 'lumnezia',
    'vignogn': 'lumnezia',
    'wolfgang': 'davos',

    # JU
    'bassecourt': 'haute-sorne',
    'courfaivre': 'haute-sorne',
    'courtemautruy': 'haute-ajoie',
    'delsberg': 'delémont',
    'glovelier': 'haute-sorne',
    'miécourt': 'haute-ajoie',
    'montignez': 'basse-allaine',
    'pruntrut': 'porrentruy',
    'st-ursanne': 'clos du doubs',
    'undervelier': 'haute-sorne',
    'vermes': 'val terbi',
    'vicques': 'val terbi',

    # LU
    'aesch lu': 'aesch (lu)',
    'altwis': 'hitzkirch',
    'emmenbrücke': 'emmen',
    'eschenbach': 'eschenbach (lu)',
    'eschenbach lu': 'eschenbach (lu)',
    'escholzmatt': 'escholzmatt-marbach',
    'gettnau': 'willisau',
    'gunzwil': 'beromünster',
    'hellbühl': 'neuenkirch',
    'kastanienbaum': 'horw',
    'langnau b. reiden': 'reiden',
    'lucerne': 'luzern',
    'marbach lu': 'escholzmatt-marbach',
    'oberkirch lu': 'oberkirch',
    'pfeffikon lu': 'beromünster',
    'richenthal': 'reiden',
    'rickenbach lu': 'rickenbach (lu)',
    'schwarzenbach lu': 'beromünster',
    'sempach station': 'neuenkirch',
    'st. niklausen lu': 'horw',
    'st. urban': 'pfaffnau',
    'sörenberg': 'flühli',
    'wiggen': 'escholzmatt-marbach',
    'winikon': 'triengen',
    'zell lu': 'zell (lu)',

    # NE
    'areuse': 'boudry',
    'bevaix': 'la grande béroche',
    'bôle': 'milvignes',
    'cernier': 'val-de-ruz',
    'chez-le-bart': 'la grande béroche',
    'chézard-st-martin': 'val-de-ruz',
    'colombier': 'milvignes',
    'colombier ne': 'milvignes',
    'corcelles ne': 'neuchâtel',
    'cressier': 'cressier (ne)',
    'cressier ne': 'cressier (ne)',
    'couvet': 'val-de-travers',
    'dombresson': 'val-de-ruz',
    'fleurier': 'val-de-travers',
    'fontainemelon': 'val-de-ruz',
    'hauterive ne': 'neuchâtel',
    'le landeron': 'le landeron',
    'marin-epagnier': 'laténa',
    'môtiers ne': 'val-de-travers',
    'neuenburg': 'neuchâtel',
    'noiraigue': 'val-de-travers',
    'peseux': 'neuchâtel',
    'st-aubin ne': 'la grande béroche',
    'st-aubin-sauges': 'la grande béroche',
    'travers': 'val-de-travers',
    'vaumarcus': 'la grande béroche',

    # NW
    'hergiswil nw': 'hergiswil (nw)',
    'fürigen': 'stansstad',

    # OW
    'alpnachstad': 'alpnach',
    'lungern ow': 'lungern',
    'stalden (sarnen)': 'sarnen',
    'wilen (sarnen)': 'sarnen',

    # SG
    'abtwil': 'gaiserwald',
    'abtwil sg': 'gaiserwald',
    'alt st. johann': 'wildhaus-alt st. johann',
    'altenrhein': 'thal',
    'altstätten sg': 'altstätten',
    'andwil sg': 'andwil (sg)',
    'arnegg': 'gossau (sg)',
    'au sg': 'au (sg)',
    'azmoos': 'wartau',
    'bazenheid': 'kirchberg (sg)',
    'benken sg': 'benken (sg)',
    'berg sg': 'berg (sg)',
    'bichwil': 'oberuzwil',
    'bronschhofen': 'wil (sg)',
    'brunnadern': 'neckertal',
    'buchs sg': 'buchs (sg)',
    'bütschwil': 'bütschwil-ganterschwil',
    'dietfurt': 'bütschwil-ganterschwil',
    'eschenbach sg': 'eschenbach (sg)',
    'goldach sg': 'goldach',
    'gossau': 'gossau (sg)',
    'gossau sg': 'gossau (sg)',
    'haag (rheintal)': 'sennwald',
    'heerbrugg': 'au (sg)',
    'jona': 'rapperswil-jona',
    'kirchberg sg': 'kirchberg (sg)',
    'kriessern': 'oberriet (sg)',
    'lüchingen': 'altstätten',
    'marbach sg': 'marbach (sg)',
    'mogelsberg': 'neckertal',
    'neu st. johann': 'nesslau',
    'niederglatt sg': 'oberuzwil',
    'niederwil sg': 'oberbüren',
    'oberriet': 'oberriet (sg)',
    'oberriet sg': 'oberriet (sg)',
    'rapperswil': 'rapperswil-jona',
    'rapperswil sg': 'rapperswil-jona',
    'rapperswil-jona': 'rapperswil-jona',
    'rüthi': 'rüthi (sg)',
    'rüthi (rheintal)': 'rüthi (sg)',
    'sankt margrethen': 'st. margrethen',
    'schwarzenbach sg': 'jonschwil',
    'st. gallen': 'st. gallen',
    'st. margrethen sg': 'st. margrethen',
    'st.gallen': 'st. gallen',
    'staad': 'thal',
    'staad sg': 'thal',
    'trübbach': 'wartau',
    'wagen': 'rapperswil-jona',
    'wil': 'wil (sg)',
    'wil sg': 'wil (sg)',
    'wildhaus': 'wildhaus-alt st. johann',
    'zuzwil sg': 'zuzwil (sg)',

    # SH
    '8212 neuhausen am rheinfall': 'neuhausen am rheinfall',
    'bargen sh': 'bargen (sh)',
    'hofen sh': 'thayngen',
    'neuhausen': 'neuhausen am rheinfall',

    # SO
    'aeschi': 'aeschi (so)',
    'beinwil': 'beinwil (so)',
    'däniken so': 'däniken',
    'erlinsbach so': 'erlinsbach (so)',
    'flüh': 'hofstetten-flüh',
    'hofstetten so': 'hofstetten-flüh',
    'kappel': 'kappel (so)',
    'kappel so': 'kappel (so)',
    'kyburg-buchegg': 'buchegg',
    'lohn ammannsegg': 'lohn-ammannsegg',
    'mariastein': 'metzerlen-mariastein',
    'metzerlen': 'metzerlen-mariastein',
    'mümliswil': 'mümliswil-ramiswil',
    'niedererlinsbach': 'erlinsbach (so)',
    'oberdorf': 'oberdorf (so)',
    'oberdorf so': 'oberdorf (so)',
    'rickenbach': 'rickenbach (so)',
    'rickenbach so': 'rickenbach (so)',
    'seewen so': 'seewen',
    'wangen b. olten': 'wangen bei olten',
    'winistorf': 'drei höfe',

    # SZ
    'bäch': 'freienbach',
    'bäch sz': 'freienbach',
    'buttikon sz': 'schübelbach',
    'goldau': 'arth',
    'immensee': 'küssnacht (sz)',
    'küssnacht am rigi': 'küssnacht (sz)',
    'lachen sz': 'lachen',
    'merlischachen': 'küssnacht (sz)',
    'pfäffikon sz': 'freienbach',
    'rickenbach b. schwyz': 'schwyz',
    'schindellegi': 'feusisberg',
    'seewen sz': 'schwyz',
    'siebnen': 'wangen (sz)',
    'stoos sz': 'morschach',
    'wangen sz': 'wangen (sz)',
    'wilen b. wollerau': 'freienbach',

    # TG
    'andwil tg': 'birwinken',
    'au tg': 'fischingen',
    'balterswil': 'bichelsee-balterswil',
    'berg': 'berg (tg)',
    'berg tg': 'berg (tg)',
    'buch b. märwil': 'affeltrangen',
    'bürglen': 'bürglen (tg)',
    'bürglen tg': 'bürglen (tg)',
    'dettighofen': 'pfyn',
    'donzhausen': 'sulgen',
    'dussnang': 'fischingen',
    'eschlikon tg': 'eschlikon',
    'freidorf tg': 'roggwil (tg)',
    'hauptwil': 'hauptwil-gottshaus',
    'islikon': 'gachnang',
    'kefikon tg': 'gachnang',
    'kradolf': 'kradolf-schönenberg',
    'landschlacht': 'münsterlingen',
    'müllheim dorf': 'müllheim',
    'münchwilen': 'münchwilen (tg)',
    'münchwilen tg': 'münchwilen (tg)',
    'neukirch (egnach)': 'egnach',
    'neukirch an der thur': 'kradolf-schönenberg',
    'oberaach': 'amriswil',
    'oberwangen tg': 'fischingen',
    'ottoberg': 'märstetten',
    'rickenbach': 'rickenbach (tg)',
    'rickenbach b. wil': 'rickenbach (tg)',
    'scherzingen': 'münsterlingen',
    'schlatt tg': 'schlatt (tg)',
    'schlattingen': 'basadingen-schlattingen',
    'sitterdorf': 'zihlschlacht-sitterdorf',
    'stachen': 'arbon',
    'tobel': 'tobel-tägerschen',
    'uesslingen': 'uesslingen-buch',
    'warth': 'warth-weiningen',
    'wilen': 'wilen (tg)',
    'wilen b. wil': 'wilen (tg)',

    # TI
    'arbedo': 'arbedo-castione',
    'barbengo': 'lugano',
    'bodio ti': 'bodio',
    'breganzona': 'lugano',
    'brè sopra lugano': 'lugano',
    'cadro': 'lugano',
    'camorino': 'bellinzona',
    'carona': 'lugano',
    'castagnola': 'lugano',
    'castione': 'arbedo-castione',
    'cavigliano': 'terre di pedemonte',
    'claro': 'bellinzona',
    'collina d\'oro': 'collina d\'oro',
    'cugnasco': 'cugnasco-gerra',
    'davesco-soragno': 'lugano',
    'gentilino': 'collina d\'oro',
    'gerra (gambarogno)': 'gambarogno',
    'giubiasco': 'bellinzona',
    'golino': 'centovalli',
    'gorduno': 'bellinzona',
    'ligornetto': 'mendrisio',
    'locarno monti': 'locarno',
    'lodrino': 'riviera',
    'magadino': 'gambarogno',
    'malvaglia': 'serravalle',
    'massagno': 'massagno',
    'minusio': 'minusio',
    'moleno': 'bellinzona',
    'montagnola': 'collina d\'oro',
    'monte carasso': 'bellinzona',
    'osogna': 'riviera',
    'pambio-noranco': 'lugano',
    'pazzallo': 'lugano',
    'pianezzo': 'bellinzona',
    'ponte tresa': 'tresa',
    'pregassona': 'lugano',
    'preonzo': 'bellinzona',
    'quartino': 'gambarogno',
    'rancate': 'mendrisio',
    'rivera': 'monteceneri',
    'roveredo ti': 'capriasca',
    's. antonino': 'sant\'antonino',
    's. pietro': 'stabio',
    'solduno': 'locarno',
    'sonvico': 'lugano',
    'tenero': 'tenero-contra',
    'tesserete': 'capriasca',
    'verscio': 'terre di pedemonte',
    'viganello': 'lugano',
    'vira (gambarogno)': 'gambarogno',

    # UR
    'altdorf': 'altdorf (ur)',
    'altdorf ur': 'altdorf (ur)',

    # VD
    'apples': 'hautemorges',
    'bellerive vd': 'vully-les-lacs',
    'blonay': 'blonay - saint-légier',
    'bussigny-près-lausanne': 'bussigny',
    'bussy-chardonney': 'hautemorges',
    'chailly-montreux': 'montreux',
    'chavannes-renens': 'chavannes-près-renens',
    'chesières': 'ollon',
    'clarens': 'montreux',
    'combremont-le-petit': 'valbroye',
    'corcelles-payerne': 'corcelles-près-payerne',
    'cossonay-ville': 'cossonay',
    'crans vd': 'crans (vd)',
    'cully': 'bourg-en-lavaux',
    'ecublens': 'ecublens (vd)',
    'ecublens vd': 'ecublens (vd)',
    'ferlens vd': 'jorat-mézières',
    'glion': 'montreux',
    'granges-près-marnand': 'valbroye',
    'lausanne 25': 'lausanne',
    'le mont-pèlerin': 'chardonne',
    'le mont-sur-lausanne': 'le mont-sur-lausanne',
    'le pont': 'l\'abbaye',
    'le sentier': 'le chenit',
    'le sépey': 'ormont-dessous',
    'les bioux': 'l\'abbaye',
    'les diablerets': 'ormont-dessus',
    'les mosses': 'ormont-dessous',
    'lully vd': 'lully (vd)',
    'mex vd': 'mex (vd)',
    'mur (vully) vd': 'vully-les-lacs',
    'mézières vd': 'jorat-mézières',
    'ollon vd': 'ollon',
    'onnens vd': 'onnens (vd)',
    'oron-la-ville': 'oron',
    'palézieux': 'oron',
    'renens': 'renens (vd)',
    'renens vd': 'renens (vd)',
    'roche vd': 'roche (vd)',
    'romanel-s-lausanne': 'romanel-sur-lausanne',
    'st-cergue': 'saint-cergue',
    'st-légier-la chiésaz': 'blonay - saint-légier',
    'st-prex': 'saint-prex',
    'st-saphorin (lavaux)': 'saint-saphorin (lavaux)',
    'st-sulpice': 'saint-sulpice (vd)',
    'st-sulpice vd': 'saint-sulpice (vd)',
    'ste-croix': 'sainte-croix',
    'territet': 'montreux',
    'villeneuve vd': 'villeneuve (vd)',
    'yverdon': 'yverdon-les-bains',

    # VS
    'aproz (nendaz)': 'nendaz',
    'blatten b. naters': 'naters',
    'brig': 'brig-glis',
    'charrat': 'martigny',
    'chermignon': 'crans-montana',
    'collombey': 'collombey-muraz',
    'crans': 'crans-montana',
    'crans-sur-sierre': 'crans-montana',
    'gampel': 'gampel-bratsch',
    'glis': 'brig-glis',
    'granges vs': 'sierre',
    'haute-nendaz': 'nendaz',
    'les collons': 'vex',
    'martigny-croix': 'martigny-combe',
    'mayens-de-chamoson': 'chamoson',
    'mollens vs': 'crans-montana',
    'montana': 'crans-montana',
    'morgins': 'troistorrents',
    'muraz': 'collombey-muraz',
    'mörel': 'mörel-filet',
    'ovronnaz': 'leytron',
    'randogne': 'crans-montana',
    'ried brig': 'ried-brig',
    'siders': 'sierre',
    'sion': 'sion',
    'sitten': 'sion',
    'st-luc': 'anniviers',
    'st-martin vs': 'saint-martin (vs)',
    'st-maurice': 'saint-maurice',
    'stalden vs': 'stalden (vs)',
    'steg vs': 'steg-hohtenn',
    'susten': 'leuk',
    'verbier': 'val de bagnes',
    'vercorin': 'chalais',
    'vissoie': 'anniviers',
    'zinal': 'anniviers',

    # ZH
    'adlikon b. regensdorf': 'regensdorf',
    'aesch zh': 'aesch (zh)',
    'au zh': 'wädenswil',
    'au-wädenswil': 'wädenswil',
    'baltenswil': 'bassersdorf',
    'birmensdorf': 'birmensdorf (zh)',
    'birmensdorf zh': 'birmensdorf (zh)',
    'buchs': 'buchs (zh)',
    'buchs zh': 'buchs (zh)',
    'dänikon zh': 'dänikon',
    'egg b. zürich': 'egg',
    'erlenbach': 'erlenbach (zh)',
    'erlenbach zh': 'erlenbach (zh)',
    'forch': 'maur',
    'glattbrugg': 'opfikon',
    'glattpark': 'opfikon',
    'glattpark (opfikon)': 'opfikon',
    'gossau': 'gossau (zh)',
    'gossau zh': 'gossau (zh)',
    'grüt (gossau zh)': 'gossau (zh)',
    'kilchberg': 'kilchberg (zh)',
    'kilchberg zh': 'kilchberg (zh)',
    'küsnacht': 'küsnacht (zh)',
    'küsnacht zh': 'küsnacht (zh)',
    'laupen zh': 'wald (zh)',
    'nänikon': 'uster',
    'niederglatt zh': 'niederglatt',
    'oberglatt zh': 'oberglatt',
    'oberwinterthur': 'winterthur',
    'oerlikon': 'zürich',
    'oetwil a.d.l.': 'oetwil an der limmat',
    'pfäffikon': 'pfäffikon',
    'pfäffikon zh': 'pfäffikon',
    'rickenbach zh': 'rickenbach (zh)',
    'rüti': 'rüti (zh)',
    'rüti zh': 'rüti (zh)',
    'tann': 'dürnten',
    'uitikon waldegg': 'uitikon',
    'wald': 'wald (zh)',
    'wald zh': 'wald (zh)',
    'weiningen': 'weiningen (zh)',
    'weiningen zh': 'weiningen (zh)',
    'wetzikon': 'wetzikon (zh)',
    'wetzikon zh': 'wetzikon (zh)',
    'wil': 'wil (zh)',
    'winterthur-seen': 'winterthur',
    'zh': 'zürich',
    'zollikerberg': 'zollikon',
    'zurich': 'zürich',
    'zurigo': 'zürich',

        # -- Top 20 Mismatch Fixes --
    'effretikon': 'illnau-effretikon',
    'illnau': 'illnau-effretikon',
    'aminona': 'crans-montana',
    'niederuzwil': 'uzwil',
    'capolago': 'mendrisio',
    'arzo': 'mendrisio',
    'bruegg be': 'bruegg', # Handle "Brügg BE"
    'langwiesen': 'feuerthalen',
    'bouveret': 'port-valais', # The village is Bouveret, commune is Port-Valais
    'les posses-sur-bex': 'bex',
    'brunnen': 'ingenbohl', # Famous one: Brunnen is the town, Ingenbohl is the commune
    'la conversion': 'lutry',
    'romont fr': 'romont',
    'chenaux': 'bourg-en-lavaux', # Part of Cully, which merged into Bourg-en-Lavaux
    'agra': 'collina d\'oro',
    'berlens': 'mezieres', # Merged into Mézières (FR)
    'ruvigliana': 'lugano',
    'les brenets': 'le locle', # Merged recently (2024)
    'taverne': 'torricella-taverne',
    'les pontins': 'saint-imier',
    
    # -- Others likely in your tail --
    'crans-pres-celigny': 'crans',
    'le lignon': 'vernier',
    'conches': 'chene-bougeries',
    'thun 1': 'thun', # Scraper artifact
}
